In [7]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5])
view_array = original_array[1:4] # Slicing creates a view

print(f"Original array: {original_array}")
print(f"View array: {view_array}")

Original array: [1 2 3 4 5]
View array: [2 3 4]


In [12]:
print(original_array.base)
print(original_array.flags['OWNDATA'])


None
True


In [13]:
print(view_array.base)
print(view_array.flags['OWNDATA'])
print(view_array.flags)

[1 2 3 4 5]
False
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [3]:
view_array[0] = 99 # Modifying the view

print(f"Original array after view modification: {original_array}")
print(f"View array after modification: {view_array}")

Original array after view modification: [ 1 99  3  4  5]
View array after modification: [99  3  4]


https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing

## Basic indexing

### Single-element indexing
- zero based
- accepts negative indices for indexing from the end of the array

In [15]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
print(x[2])
print(x[-2])

2
8


It is not necessary to separate each dimension’s index into its own set of square brackets.

In [19]:
x.shape = (2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
x[1,3]

8

In [21]:
x[1,-1]

9

if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array. 

In [22]:
x[0]

array([0, 1, 2, 3, 4])

In [25]:
print(x[0].base)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [27]:
x[0][2]

2

In [28]:
x[0,2]

2

### Basic slicing


In [29]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

Negative i and j are interpreted as n + i and n + j where n is the number of elements in the corresponding dimension. Negative k makes stepping go towards smaller indices. From the above example:

In [33]:
print(x[-2:10])
print(x[-2:11])

[8 9]
[8 9]


In [35]:
print(x[-3:3])

[]


In [36]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [37]:
print(x[5:])

[5 6 7 8 9]


In [38]:
print(x[::])

[0 1 2 3 4 5 6 7 8 9]


In [40]:
print(x[:])

[0 1 2 3 4 5 6 7 8 9]


In [41]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [42]:
x.shape

(2, 3, 1)

In [43]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [47]:
y = np.array([[[1,2],[2,1],[3,6]], [[4,5],[4,5],[1,6]]])
y

array([[[1, 2],
        [2, 1],
        [3, 6]],

       [[4, 5],
        [4, 5],
        [1, 6]]])

In [48]:
x[0]

array([[1],
       [2],
       [3]])

In [51]:
x[0].shape

(3, 1)

In [50]:
x[0:1]

array([[[1],
        [2],
        [3]]])

In [52]:
x[0:1].shape

(1, 3, 1)

In [54]:
x[1:10:5]

array([[[4],
        [5],
        [6]]])

In [53]:
x[1:10:5, ::-1]

array([[[6],
        [5],
        [4]]])

In [55]:
obj = (slice(1, 10, 5), slice(None, None, -1))
x[obj]

array([[[6],
        [5],
        [4]]])

In [56]:
x.ndim

3

In [58]:
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [57]:
x[..., 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
x[:, :, 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
x[:,:,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
obj.nonzero()

AttributeError: 'tuple' object has no attribute 'nonzero'