## Book section between Ex 9-10: Retrieving and assigning with loc (pg. 47)

In [1]:
!python --version
!which python

Python 3.11.13
/opt/anaconda3/envs/py311b/bin/python


In [88]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [89]:
mylist = [n for n in range(10,251,10)]
len(mylist)

25

In [90]:
arr = np.array(mylist)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250])

In [91]:
arr.reshape(5,5)  # no inplace effect
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250])

In [92]:
id(arr)

13594177776

In [93]:
arr = arr.reshape(5,5)  # use arr = arr... to modify "inplace"; 
# actually it's a new object
arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [94]:
id(arr)  # arr is a new object

13593786192

In [95]:
df = DataFrame(arr, columns=list('vwxyz'), index=list('abcde'))
df

v    w    x    y    z
a   10   20   30   40   50
b   60   70   80   90  100
c  110  120  130  140  150
d  160  170  180  190  200
e  210  220  230  240  250

In [96]:
df.to_csv('df-abcde-vwxyz.csv')

In [12]:
df.loc['a']

v    10
w    20
x    30
y    40
z    50
Name: a, dtype: int64

In [35]:
df.loc['a','x']

30

In [37]:
df.loc[['a','c'],'x']

a     30
c    130
Name: x, dtype: int64

In [38]:
df.loc['a', ['v', 'y']]

v    10
y    40
Name: a, dtype: int64

In [13]:
df

v    w    x    y    z
a   10   20   30   40   50
b   60   70   80   90  100
c  110  120  130  140  150
d  160  170  180  190  200
e  210  220  230  240  250

In [39]:
df.loc[['a','c'], ['v', 'y']]

v    y
a   10   40
c  110  140

In [14]:
# all rows where x > 200
df['x']>200

a    False
b    False
c    False
d    False
e     True
Name: x, dtype: bool

In [15]:
# all rows where x > 200
df.loc[df['x']>200]


v    w    x    y    z
e  210  220  230  240  250

In [17]:
df

v    w    x    y    z
a   10   20   30   40   50
b   60   70   80   90  100
c  110  120  130  140  150
d  160  170  180  190  200
e  210  220  230  240  250

In [22]:
df.loc[['a','e']]

v    w    x    y    z
a   10   20   30   40   50
e  210  220  230  240  250

In [36]:
# which rows have x > 200
df['x'] > 200

a    False
b    False
c    False
d    False
e     True
Name: x, dtype: bool

In [37]:
# select rows where x > 200
df.loc[df['x']>200]

v    w    x    y    z
e  210  220  230  240  250

In [38]:
# which columns have c > 135
df.loc['c'] > 135

v    False
w    False
x    False
y     True
z     True
Name: c, dtype: bool

In [41]:
# in the rows where x > 200 (i.e., row e), which cells in row e are in the column(s) 
# where c > 135
df.loc[df['x']>200,df.loc['c']>135]

y    z
e  240  250

In [43]:
df

v    w    x    y    z
a   10   20   30   40   50
b   60   70   80   90  100
c  110  120  130  140  150
d  160  170  180  190  200
e  210  220  230  240  250

In [42]:
# We are interested in row b, but only where c > 135

In [45]:
df.loc['b']

v     60
w     70
x     80
y     90
z    100
Name: b, dtype: int64

In [47]:
df.loc['c']>135

v    False
w    False
x    False
y     True
z     True
Name: c, dtype: bool

In [51]:
df.loc['b',df.loc['c']>135]

y     90
z    100
Name: b, dtype: int64

 select based on rows before the comma and based on
columns after the comma, 

# Exercise 10 - Adding new products

In [53]:
import pandas as pd
from pandas import Series, DataFrame

df = DataFrame([{'product_id':23, 'name':'computer', 'wholesale_price': 500,
                 'retail_price':1000, 'sales':100},
               {'product_id':96, 'name':'Python Workout', 'wholesale_price': 35,
                'retail_price':75, 'sales':1000},
               {'product_id':97, 'name':'Pandas Workout', 'wholesale_price': 35,
                'retail_price':75, 'sales':500},
               {'product_id':15, 'name':'banana', 'wholesale_price': 0.5,
                'retail_price':1, 'sales':200},
               {'product_id':87, 'name':'sandwich', 'wholesale_price': 3,
                'retail_price':5, 'sales':300},
               ])

df

product_id            name  wholesale_price  retail_price  sales
0          23        computer            500.0          1000    100
1          96  Python Workout             35.0            75   1000
2          97  Pandas Workout             35.0            75    500
3          15          banana              0.5             1    200
4          87        sandwich              3.0             5    300

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   product_id       5 non-null      int64  
 1   name             5 non-null      object 
 2   wholesale_price  5 non-null      float64
 3   retail_price     5 non-null      int64  
 4   sales            5 non-null      int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 332.0+ bytes


Note: sales is int64

In [54]:
new_products = DataFrame([{'product_id':24, 'name':'phone', 'wholesale_price': 200,
                 'retail_price':500},
                        {'product_id':16, 'name':'apple', 'wholesale_price': 0.5,
                 'retail_price':1},
                        {'product_id':17, 'name':'pear', 'wholesale_price': 0.6,
                 'retail_price':1.2}], index=range(5,8))
new_products

product_id   name  wholesale_price  retail_price
5          24  phone            200.0         500.0
6          16  apple              0.5           1.0
7          17   pear              0.6           1.2

In [73]:
new_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 5 to 7
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   product_id       3 non-null      int64  
 1   name             3 non-null      object 
 2   wholesale_price  3 non-null      float64
 3   retail_price     3 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 228.0+ bytes


In [58]:
df2 = pd.concat([df, new_products])
df2

product_id            name  wholesale_price  retail_price   sales
0          23        computer            500.0        1000.0   100.0
1          96  Python Workout             35.0          75.0  1000.0
2          97  Pandas Workout             35.0          75.0   500.0
3          15          banana              0.5           1.0   200.0
4          87        sandwich              3.0           5.0   300.0
5          24           phone            200.0         500.0     NaN
6          16           apple              0.5           1.0     NaN
7          17            pear              0.6           1.2     NaN

In [74]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   product_id       8 non-null      int64  
 1   name             8 non-null      object 
 2   wholesale_price  8 non-null      float64
 3   retail_price     8 non-null      float64
 4   sales            8 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 452.0+ bytes


Sales is now float64

In [64]:
# set sales values for the new products, [100, 200, 75]
df2.loc[[5,6,7],'sales']

5   NaN
6   NaN
7   NaN
Name: sales, dtype: float64

In [66]:
df2.loc[[5,6,7],'sales'] = [100,200,75]
df2

product_id            name  wholesale_price  retail_price   sales
0          23        computer            500.0        1000.0   100.0
1          96  Python Workout             35.0          75.0  1000.0
2          97  Pandas Workout             35.0          75.0   500.0
3          15          banana              0.5           1.0   200.0
4          87        sandwich              3.0           5.0   300.0
5          24           phone            200.0         500.0   100.0
6          16           apple              0.5           1.0   200.0
7          17            pear              0.6           1.2    75.0

In [78]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   product_id       8 non-null      int64  
 1   name             8 non-null      object 
 2   wholesale_price  8 non-null      float64
 3   retail_price     8 non-null      float64
 4   sales            8 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 452.0+ bytes


In [81]:
# (retail - wholesale) * sales
((df2['retail_price'] - df2['wholesale_price']) * df2['sales']).sum()

140845.0

In [82]:
df2.dtypes

product_id           int64
name                object
wholesale_price    float64
retail_price       float64
sales              float64
dtype: object

In [86]:
df3 = df2.astype({'sales':int})
df3.dtypes

product_id           int64
name                object
wholesale_price    float64
retail_price       float64
sales                int64
dtype: object

In [87]:
df3

product_id            name  wholesale_price  retail_price  sales
0          23        computer            500.0        1000.0    100
1          96  Python Workout             35.0          75.0   1000
2          97  Pandas Workout             35.0          75.0    500
3          15          banana              0.5           1.0    200
4          87        sandwich              3.0           5.0    300
5          24           phone            200.0         500.0    100
6          16           apple              0.5           1.0    200
7          17            pear              0.6           1.2     75

In [107]:
df3.to_csv('products.csv')

# Query method, page 5

In [100]:
df = pd.read_csv('df-abcde-vwxyz.csv', index_col=0)
df

v    w    x    y    z
a   10   20   30   40   50
b   60   70   80   90  100
c  110  120  130  140  150
d  160  170  180  190  200
e  210  220  230  240  250

In [101]:
df['v']> 100

a    False
b    False
c     True
d     True
e     True
Name: v, dtype: bool

In [102]:
df.loc[df['v']>100]

v    w    x    y    z
c  110  120  130  140  150
d  160  170  180  190  200
e  210  220  230  240  250

In [103]:
df.query('v > 100')

v    w    x    y    z
c  110  120  130  140  150
d  160  170  180  190  200
e  210  220  230  240  250

In [104]:
df.query('v > 100 & w % 20 == 0')

v    w    x    y    z
c  110  120  130  140  150
e  210  220  230  240  250